### ISSUE TITLE
http and maniaplanet link parser doesn't add protocol

### ISSUE THREAD

**Issue by reaby** [maniaplanet/maniaplanet-style-js-parser#2]
$f20Some red text,$z$o a little bold, $z$l[http://magnetik.org]and a link$l

link outcome: 
http://magnetik.org/

    $f20Some red text,$z$o a little bold, $z$l[magnetik.org]and a link$l

link outcome:
http://magnetik.github.io/maniaplanet-style-js-parser/magnetik.org

expected outcome:
http://magnetik.org

**Comment by magnetik** [comment]
I think it works well with latest version

**Comment by magnetik** [comment]
It was not, but I think it's okay now. See the tests added in 7a3159f04160c6a6104fbee60fa21ec1a1fd717d
