### ISSUE TITLE
Parsing invalid tags is done wrongly

### ISSUE THREAD

**Issue by ghost** [maniaplanet/maniaplanet-style-js-parser#3]
Parsing things such as `$uhi there` results in `<span style="color: #000000;"> there</span>` (`$uhi` seen as color?).
ManiaPlanet parses this to `hi there` (without style changes, `$u` stripped).

Maybe it's useful to mention that even if legal color symbols follow after the `$u`, the color does not change. E.g. `$uff there` also results in `<span style="color: #000000;"> there</span>`.

**Comment by magnetik** [comment]
Fixed the `$uhi there` and I've added tests
